# Generated by Django 3.0.8 on 2020-07-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebotdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=50, verbose_name='chat_id')),
                ('name', models.TextField(verbose_name='name')),
            ],
        ),
    ]
